baseURL = "/"
title = "Fascination of Plants"
theme = "plants-theme"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]

[languages.en]
languageName = "English"
weight = 1
contentDir = "content/en"

[languages.nl]
languageName = "Nederlands"
weight = 2
contentDir = "content/nl"

[menu]

# --- HOME ---
[[menu.main]]
name = "Home"
pageRef = "_index"
weight = 1

# --- EXHIBITIONS (parent) ---
[[menu.main]]
name = "Exhibitions"
identifier = "exhibitions"
weight = 2

[[menu.main]]
name = "Exhibition 2024"
pageRef = "exhibitions/2024"
parent = "exhibitions"
weight = 1

[[menu.main]] 
name = "Exhibition 2026 - Current"
pageRef = "exhibitions/2026"
parent = "exhibitions"
weight = 2

# --- CURRENT EXHIBITION (parent) ---
[[menu.main]]
name = "Current exhibition"
identifier = "current"
weight = 3

[[menu.main]]
name = "Closing event 2026"
pageRef = "closing-event"
parent = "current"
weight = 1

[[menu.main]]
name = "Participate"
pageRef = "form"
parent = "current"
weight = 2

# --- ABOUT (parent) ---
[[menu.main]]
name = "About"
identifier = "about"
weight = 4

[[menu.main]]
name = "Acknowledgements"
pageRef = "ack"
parent = "about"
weight = 1

[[menu.main]]
name = "Contact"
pageRef = "contact"
parent = "about"
weight = 2