baseURL = "http://localhost:1313/"
title = "Fascination of Plants"
theme = "plants-theme"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]

[languages.en]
languageName = "English"
weight = 1
contentDir = "content/en"

[languages.nl]
languageName = "Nederlands"
weight = 2
contentDir = "content/nl"

[menu]
[[menu.main]]
name = "Home"
pageRef = "_index"
weight = 1

[[menu.main]]
name = "Exhibitions"
pageRef = "exhibitions"
weight = 2

[[menu.main]]
name = "Closing Event"
pageRef = "closing-event"
weight = 3

[[menu.main]]
name = "Form"
pageRef = "form"
weight = 4