baseURL = "https://felaberecochea.github.io/Fop/"
title = "Fascination of Plants"
theme = "plants-theme"

defaultContentLanguage = "en"
defaultContentLanguageInSubdir = true

[languages]
  [languages.en]
    weight = 1
    languageName = "English"
    contentDir = "content"

  [languages.nl]
    weight = 2
    languageName = "Nederlands"
    contentDir = "content"